### ISSUE TITLE
Support for Proto3 well known types

### ISSUE THREAD

**Issue by ethiery** [protostuff/protobuf-jetbrains-plugin#135] opened 2019-03-17 11:28 UTC
First of all, thanks for this plugin, very useful.

**Is your feature request related to a problem? Please describe.**
I am using proto3, and importing some well know types. It seems that these are not currently supported out of box, since I am getting a "File not found" error on the import, and an "Unresolved reference" error on all usages.

**Describe the solution you'd like**
It would be great if [protobuf/src/google/protobuf/](https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf) was automatically added as an include path of this plugin. 

**Additional context**

Example:

```proto
syntax = "proto3";

import "google/protobuf/timestamp.proto";

package myproto;

message MyMessage {
    google.protobuf.Timestamp created_at = 1;
}
```

**Comment by kshchepanovskyi** [comment] 2019-03-17 11:39
It should work already this way. What plugin version are you using?

**Comment by kshchepanovskyi** [comment] 2019-03-17 11:44
![image](https://user-images.githubusercontent.com/4040120/54489996-b936bd00-48ba-11e9-937c-a7096ac1ce3c.png)

**Comment by ethiery** [comment] 2019-03-18 10:03
Using v0.13.0 in Goland 2018.3.5.

I just tried opening the same .proto file with IntelliJ Ultimate 2018.3.5, and it works as expected. Navigating to the declaration of `google.protobuf.Timestamp` shows that it is pulled from a protobuf jar packaged with the plugin (~/.IntelliJIdea2018.3/config/plugins/protobuf-jetbrains-plugin/lib/protobuf-java-3.6.1-sources.jar!/google/protobuf/timestamp.proto).

I found the same jar under  /.GoLand2018.3/config/plugins/protobuf-jetbrains-plugin/lib/, but for some reason its content does not seem to be in the include paths of the plugin in GoLand.

For the record, manually adding a path to the well known types in the include paths of the plugin works:
```
go get -d github.com/protocolbuffers/protobuf
```
![image](https://user-images.githubusercontent.com/13584434/54522380-f8b9e380-4964-11e9-89d7-6458ce5bab6a.png)


Let me know if there is anything else I can do to help diagnose

**Comment by kshchepanovskyi** [comment] 2019-03-18 19:55
Works for me in GoLand 2018.3.5:

![image](https://user-images.githubusercontent.com/4040120/54559312-6c410c80-49c8-11e9-9c6a-8eda0b873a41.png)

Can you please create minimal project that reproduces an issue, archive it and attach here?

**Comment by kshchepanovskyi** [comment] 2019-03-18 20:16
In IntelliJ IDEA libraries are visible in "Project Structure" dialog. Unfortunately, I could not find it in GoLand.
However, we can check library settings manually in `<project name>.iml` file inside `.idea/` folder in project directory:

```xml
kshchepanovskyi@ks-laptop:~/go/src/awesomeProject/.idea$ cat awesomeProject.iml 
<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$" />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="Bundled Protobuf Distribution" level="application" />
  </component>
</module>
```

There should be `Bundled Protobuf Distribution` entry in the list.

**Comment by ethiery** [comment] 2019-03-20 09:30
Alright, I think I have isolated the issue. 

I have created [this minimum project](https://github.com/ethiery/MRE_protobuf_plugin). 
At the root, you'll find the `hello.proto` we've been discussing previously, and two folders:
- `hello_go` which contains the go code generated by protoc
- `hello_java` which contains the java code generated protoc

The issue occurs if you:
- open `/hello_go` (not the root) with Goland
![image](https://user-images.githubusercontent.com/13584434/54673383-0e104880-4af2-11e9-9a64-9e32e33f0011.png)
- Within this Goland window, open `hello.proto` (which is thus outside the project). 
![image](https://user-images.githubusercontent.com/13584434/54673487-444dc800-4af2-11e9-9961-743f7d8d2284.png)
- Resulting in the issue I described.
![image](https://user-images.githubusercontent.com/13584434/54673627-8840cd00-4af2-11e9-879d-9e9e207f0639.png)

For the record, `Bundled Protobuf Distribution" does not appear in `.idea/hello_go.iml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$" />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>
```

**Comment by ethiery** [comment] 2019-03-20 09:48
A few other experiments.

# Opening `/hello_go` with IntelliJ

This does not seem to be a Goland specific issue per se, since repeating the same 3 steps with IntelliJ instead of Goland leads to the same result.
![image](https://user-images.githubusercontent.com/13584434/54673966-5845f980-4af3-11e9-9dfa-1340cd351422.png)

# Opening `/hello_java` with IntelliJ
Interestingly, repeating the same 3 steps with IntelliJ and with the `hello_java` folder does not lead to any issue:
![image](https://user-images.githubusercontent.com/13584434/54674309-0b165780-4af4-11e9-91e8-72d478da18aa.png)

However, inspecting the project structure or navigating to the declaration of `google.protobuf.timestamp` show that the plugin picks it up not from the bundled protobuf distribution, but from the `"com.google.protobuf:protobuf-java:3.7.0"` gradle dependency required for the generated java code to compile. 
![image](https://user-images.githubusercontent.com/13584434/54674509-7829ed00-4af4-11e9-96fa-eed8eb5b111c.png)

# Opening `/` with Golang

Finally, opening the root folder of the repo with Goland works fine:
![image](https://user-images.githubusercontent.com/13584434/54674647-cb9c3b00-4af4-11e9-8777-759923abf67f.png)

And in that case, the bundled protobuf distribution appears in `/.idea/MRE_protobuf_plugin.iml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="Go" enabled="true" />
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$" />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
    <orderEntry type="library" name="Bundled Protobuf Distribution" level="application" />
  </component>
</module>
```

# Conclusion

So to me, the issue seems to stem from the fact that both IntelliJ and Goland seem to only include the bundled protobuf distribution if there is a .proto file within the project.

I hope that helps, thanks for the time you are spending on this.

**Comment by briantopping** [comment] 2020-05-04 20:23
Another comment here: In IntelliJ 2020.1, the plugin properly resolves the import and can navigate to the file, but the usage of types gives an unresolved reference:
<img width="383" alt="Screen Shot 2020-05-04 at 2 23 34 PM" src="https://user-images.githubusercontent.com/158115/81009997-d9a13e00-8e12-11ea-9b0f-0138fad67c78.png">

**Comment by jvolkman** [comment] 2020-05-05 16:29
@briantopping since `StringValue` isn't in your declared package, you'll need to qualify it. E.g., 
```
google.protobuf.StringValue username = 1;
```

**Comment by briantopping** [comment] 2020-05-05 16:31
Ah perfect! Wish I had realized that, thanks!!

**Comment by kshchepanovskyi** [comment] 2020-07-29 14:37
This issue is closed as plugin is not supported anymore. 
Please switch to https://github.com/jvolkman/intellij-protobuf-editor.

**Closed by kshchepanovskyi** 2020-07-29 14:37 UTC
