### ISSUE TITLE
Exception thrown with Intellij EAP 2018.3

### ISSUE THREAD

**Issue by IceMan81** [protostuff/protobuf-jetbrains-plugin#120] opened 2018-10-15 23:54 UTC
**Describe the bug**
The plugin throws an exception java.lang.IncompatibleClassChangeError

**To Reproduce**
1. Use the latest version of the plugin with 2018.3 EAP
2. Intellij throws IDE Fatal Errors

**Expected behavior**
No exceptions from the plugin

**Plugin (please complete the following information):**
 - OS: Windows 7
 - Version : v0.12.0 

**Additional context**
This is the full stack trace

```
io.protostuff.jetbrains.plugin.ProtostuffPluginController@22353110

java.lang.IncompatibleClassChangeError: Method com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable.getInstance(Lcom/intellij/openapi/project/Project;)Lcom/intellij/openapi/roots/libraries/LibraryTable; must be InterfaceMethodref 
	at io.protostuff.jetbrains.plugin.ProtostuffPluginController.findGlobalProtobufLibrary(ProtostuffPluginController.java:171)
	at io.protostuff.jetbrains.plugin.ProtostuffPluginController.updateGlobalLibrary(ProtostuffPluginController.java:140)
	at io.protostuff.jetbrains.plugin.ProtostuffPluginController.projectOpened(ProtostuffPluginController.java:87)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:793)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$6(ProjectManagerImpl.java:399)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:165)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:776)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:202)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:188)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:606)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:454)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:251)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:205)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:448)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:423)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:254)
	at com.intellij.ide.RecentProjectsManagerBase.doOpenProject(RecentProjectsManagerBase.java:578)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:697)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:742)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy67.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:370)
	at com.intellij.idea.IdeaApplication.lambda$run$1(IdeaApplication.java:211)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:211)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:723)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`
```

**Comment by kshchepanovskyi** [comment] 2018-10-16 15:57
@IceMan81 which build did you use? I tested plugin with IC-183.3647.12, works fine.

**Comment by IceMan81** [comment] 2018-10-16 16:00
That's the same build I used, except that its the ultimate edition. I'm also using https://bintray.com/jetbrains/intellij-jdk/openjdk9-osx-x64/152 as the runtime JVM

**Comment by kshchepanovskyi** [comment] 2018-10-16 16:17
Seems that this build is not very stable. I could not reproduce issue with protobuf plugin yet, but already caught few exceptions in other plugins:

![image](https://user-images.githubusercontent.com/4040120/47031209-17c70600-d178-11e8-9f9b-99a94f3f0dcd.png)

**Comment by kshchepanovskyi** [comment] 2018-10-16 16:39
Ok, I used JDK 8 that's why I could not reproduce it.

**Comment by kshchepanovskyi** [comment] 2018-10-16 16:45
Until this bug is not fixed - you can run IDEA using JDK 8 as a workaround.

**Comment by IceMan81** [comment] 2018-10-21 03:13
Thanks for checking. From the exception hard to understand why that error would be because of JDK 9. I'll raise the error with Jetbrains.

**Comment by kshchepanovskyi** [comment] 2018-11-15 17:50
https://youtrack.jetbrains.com/issue/IDEA-202322

**Comment by kshchepanovskyi** [comment] 2018-11-22 20:04
Fixed by https://github.com/protostuff/protobuf-jetbrains-plugin/commit/5267b4632216e8e92b1dc5178d78f2fa2763d626

**Closed by kshchepanovskyi** 2018-11-22 20:04 UTC
Labels: bug

**Comment by IceMan81** [comment] 2018-11-28 23:15
Will you releasing a new build with this fix? I tried to build it on my own but ran into some issues. Didn't try too hard to resolve them.

**Comment by kshchepanovskyi** [comment] 2018-12-01 11:32
Yes, soon when this scope is ready: https://github.com/protostuff/protobuf-jetbrains-plugin/milestone/17

While it's not ready, you might want to use latest plugin build from here: https://jenkins.ksprojects.org/job/protostuff/job/protobuf-jetbrains-plugin/job/master/
